export const AAC_CATEGORIES = [
  { id:'needs',    label:'I Need',       color:'#E84040', icon:'🤲' },
  { id:'feelings', label:'I Feel',       color:'#C44898', icon:'💜' },
  { id:'actions',  label:'I Want To',    color:'#3AB5D4', icon:'✋' },
  { id:'places',   label:'I Want To Go', color:'#3A9E5A', icon:'📍' },
  { id:'people',   label:'People',       color:'#E8A030', icon:'👤' },
  { id:'food',     label:'Food',         color:'#9B6AE0', icon:'🍎' },
  { id:'yes_no',   label:'Yes / No',     color:'#20C8E0', icon:'✓✗' },
  { id:'social',   label:'Social',       color:'#C4A035', icon:'👋' },
]

export const AAC_SYMBOLS = {
  needs: [
    { id:'need_water',     label:'Water',      speech:'I need water',        image:'[AAC: cup of water]',       color:'#3AB5D4' },
    { id:'need_food',      label:'Food',       speech:'I am hungry',         image:'[AAC: plate with food]',    color:'#E8A030' },
    { id:'need_bathroom',  label:'Bathroom',   speech:'I need the bathroom', image:'[AAC: bathroom symbol]',    color:'#3AB5D4' },
    { id:'need_break',     label:'Break',      speech:'I need a break',      image:'[AAC: pause symbol]',       color:'#3A9E5A' },
    { id:'need_help',      label:'Help',       speech:'I need help',         image:'[AAC: helping hands]',      color:'#C4A035' },
    { id:'need_quiet',     label:'Quiet',      speech:'I need it quiet',     image:'[AAC: shh symbol]',         color:'#7C6AE0' },
    { id:'need_sleep',     label:'Sleep',      speech:'I am tired',          image:'[AAC: sleeping moon]',      color:'#3A3A7C' },
    { id:'need_medicine',  label:'Medicine',   speech:'I need medicine',     image:'[AAC: medicine bottle]',    color:'#E84040' },
    { id:'need_warm',      label:'Warm',       speech:'I am cold',           image:'[AAC: blanket]',            color:'#E8A030' },
    { id:'need_cool',      label:'Cool Down',  speech:'I am hot',            image:'[AAC: fan or ice cube]',    color:'#3AB5D4' },
    { id:'need_hug',       label:'Hug',        speech:'I want a hug',        image:'[AAC: two arms hugging]',   color:'#C44898' },
    { id:'need_attention', label:'Look at Me', speech:'Look at me please',   image:'[AAC: eyes with arrow]',    color:'#C4A035' },
  ],
  feelings: [
    { id:'feel_happy',      label:'Happy',       speech:'I feel happy',       image:'[AAC: smiling face]',      color:'#FFD73C' },
    { id:'feel_sad',        label:'Sad',         speech:'I feel sad',         image:'[AAC: sad face]',          color:'#3AB5D4' },
    { id:'feel_angry',      label:'Angry',       speech:'I feel angry',       image:'[AAC: angry face]',        color:'#E84040' },
    { id:'feel_scared',     label:'Scared',      speech:'I feel scared',      image:'[AAC: worried face]',      color:'#7C6AE0' },
    { id:'feel_excited',    label:'Excited',     speech:'I feel excited',     image:'[AAC: excited figure]',    color:'#E8A030' },
    { id:'feel_frustrated', label:'Frustrated',  speech:'I feel frustrated',  image:'[AAC: frustrated face]',   color:'#C44898' },
    { id:'feel_tired',      label:'Tired',       speech:'I feel tired',       image:'[AAC: droopy eyes]',       color:'#3A3A7C' },
    { id:'feel_sick',       label:'Sick',        speech:'I do not feel well', image:'[AAC: sick face]',         color:'#3A9E5A' },
    { id:'feel_ok',         label:'OK',          speech:'I feel OK',          image:'[AAC: thumbs up]',         color:'#3A9E5A' },
    { id:'feel_loved',      label:'Loved',       speech:'I feel loved',       image:'[AAC: heart figure]',      color:'#C44898' },
    { id:'feel_proud',      label:'Proud',       speech:'I feel proud',       image:'[AAC: proud stance]',      color:'#C4A035' },
    { id:'feel_confused',   label:'Confused',    speech:'I am confused',      image:'[AAC: confused face]',     color:'#9B6AE0' },
    { id:'feel_calm',       label:'Calm',        speech:'I feel calm',        image:'[AAC: serene face]',       color:'#3AB5D4' },
    { id:'feel_bored',      label:'Bored',       speech:'I am bored',         image:'[AAC: bored face]',        color:'#808080' },
    { id:'feel_pain',       label:'Pain',        speech:'I am in pain',       image:'[AAC: ouch symbol]',       color:'#E84040' },
    { id:'feel_overwhelmed',label:'Overwhelmed', speech:'I feel overwhelmed', image:'[AAC: swirling lines]',    color:'#7C6AE0' },
  ],
  actions: [
    { id:'want_play',    label:'Play',       speech:'I want to play',           image:'[AAC: child playing]',      color:'#E8A030' },
    { id:'want_learn',   label:'Learn',      speech:'I want to learn',          image:'[AAC: open book]',          color:'#3AB5D4' },
    { id:'want_draw',    label:'Draw',       speech:'I want to draw',           image:'[AAC: crayon drawing]',     color:'#C44898' },
    { id:'want_music',   label:'Music',      speech:'I want to listen to music',image:'[AAC: musical notes]',     color:'#9B6AE0' },
    { id:'want_read',    label:'Read',       speech:'I want to read',           image:'[AAC: open book]',          color:'#C4A035' },
    { id:'want_talk',    label:'Talk',       speech:'I want to talk',           image:'[AAC: speech bubbles]',     color:'#3A9E5A' },
    { id:'want_watch',   label:'Watch',      speech:'I want to watch',          image:'[AAC: eyes on screen]',     color:'#3AB5D4' },
    { id:'want_outside', label:'Go Outside', speech:'I want to go outside',     image:'[AAC: door with sun]',      color:'#3A9E5A' },
    { id:'want_hug',     label:'Hug',        speech:'I want a hug',             image:'[AAC: two figures hugging]',color:'#C44898' },
    { id:'want_more',    label:'More',       speech:'I want more',              image:'[AAC: more sign]',          color:'#E8A030' },
    { id:'want_stop',    label:'Stop',       speech:'I want to stop',           image:'[AAC: stop hand]',          color:'#E84040' },
    { id:'want_help',    label:'Help',       speech:'I need help please',       image:'[AAC: helping hand]',       color:'#C4A035' },
    { id:'want_wait',    label:'Wait',       speech:'Please wait',              image:'[AAC: wait gesture]',       color:'#3AB5D4' },
    { id:'want_finish',  label:'Done',       speech:'I am done',                image:'[AAC: checkmark]',          color:'#3A9E5A' },
    { id:'want_again',   label:'Again',      speech:'I want to do it again',    image:'[AAC: repeat arrow]',       color:'#E8A030' },
    { id:'want_choose',  label:'Choose',     speech:'I want to choose',         image:'[AAC: pointing hand]',      color:'#9B6AE0' },
  ],
  places: [
    { id:'place_home',     label:'Home',     speech:'I want to go home',           image:'[AAC: house]',          color:'#E8A030' },
    { id:'place_school',   label:'School',   speech:'I want to go to school',      image:'[AAC: school building]',color:'#3AB5D4' },
    { id:'place_outside',  label:'Outside',  speech:'I want to go outside',        image:'[AAC: outdoor scene]',  color:'#3A9E5A' },
    { id:'place_bathroom', label:'Bathroom', speech:'I need the bathroom',         image:'[AAC: bathroom]',       color:'#3AB5D4' },
    { id:'place_bedroom',  label:'Bedroom',  speech:'I want to go to my room',     image:'[AAC: bedroom]',        color:'#9B6AE0' },
    { id:'place_kitchen',  label:'Kitchen',  speech:'I want to go to the kitchen', image:'[AAC: kitchen]',        color:'#E8A030' },
    { id:'place_park',     label:'Park',     speech:'I want to go to the park',    image:'[AAC: park]',           color:'#3A9E5A' },
    { id:'place_store',    label:'Store',    speech:'I want to go to the store',   image:'[AAC: store]',          color:'#C4A035' },
  ],
  people: [
    { id:'person_mom',     label:'Mom',     speech:'I want Mom',        image:'[AAC: mother figure]',  color:'#C44898' },
    { id:'person_dad',     label:'Dad',     speech:'I want Dad',        image:'[AAC: father figure]',  color:'#3AB5D4' },
    { id:'person_teacher', label:'Teacher', speech:'I want my teacher', image:'[AAC: teacher]',        color:'#C4A035' },
    { id:'person_friend',  label:'Friend',  speech:'I want my friend',  image:'[AAC: two children]',   color:'#E8A030' },
    { id:'person_doctor',  label:'Doctor',  speech:'I need a doctor',   image:'[AAC: doctor]',         color:'#E84040' },
    { id:'person_me',      label:'Me',      speech:'Me',                image:'[AAC: child pointing]', color:'#9B6AE0' },
  ],
  food: [
    { id:'food_water',  label:'Water',      speech:'Water please',          image:'[AAC: glass of water]', color:'#3AB5D4' },
    { id:'food_milk',   label:'Milk',       speech:'Milk please',           image:'[AAC: glass of milk]',  color:'#C4C4C4' },
    { id:'food_fruit',  label:'Fruit',      speech:'I want fruit',          image:'[AAC: bowl of fruit]',  color:'#E8A030' },
    { id:'food_snack',  label:'Snack',      speech:'I want a snack',        image:'[AAC: crackers]',       color:'#C4A035' },
    { id:'food_lunch',  label:'Lunch',      speech:'I want lunch',          image:'[AAC: lunch box]',      color:'#3A9E5A' },
    { id:'food_dinner', label:'Dinner',     speech:'I want dinner',         image:'[AAC: dinner plate]',   color:'#E8A030' },
    { id:'food_sweet',  label:'Sweet',      speech:'I want something sweet',image:'[AAC: cookies]',        color:'#C44898' },
    { id:'food_none',   label:'Not Hungry', speech:'I am not hungry',       image:'[AAC: empty plate x]',  color:'#808080' },
  ],
  yes_no: [
    { id:'yes',       label:'Yes',       speech:'Yes',          image:'[AAC: green checkmark]', color:'#3A9E5A' },
    { id:'no',        label:'No',        speech:'No',           image:'[AAC: red X]',           color:'#E84040' },
    { id:'maybe',     label:'Maybe',     speech:'Maybe',        image:'[AAC: question mark]',   color:'#C4A035' },
    { id:'dont_know', label:"Don't Know",speech:"I don't know", image:'[AAC: shrug]',           color:'#9B6AE0' },
    { id:'please',    label:'Please',    speech:'Please',       image:'[AAC: please gesture]',  color:'#E8A030' },
    { id:'thank_you', label:'Thank You', speech:'Thank you',    image:'[AAC: hand on heart]',   color:'#C44898' },
  ],
  social: [
    { id:'hello',     label:'Hello',     speech:'Hello',            image:'[AAC: waving hand]',      color:'#C4A035' },
    { id:'goodbye',   label:'Goodbye',   speech:'Goodbye',          image:'[AAC: waving goodbye]',   color:'#3AB5D4' },
    { id:'sorry',     label:'Sorry',     speech:'I am sorry',       image:'[AAC: apologetic gesture]',color:'#9B6AE0' },
    { id:'wait',      label:'Wait',      speech:'Wait please',      image:'[AAC: stop hand]',        color:'#E8A030' },
    { id:'come',      label:'Come Here', speech:'Come here please', image:'[AAC: beckoning hand]',   color:'#3A9E5A' },
    { id:'look',      label:'Look',      speech:'Look at this',     image:'[AAC: eyes pointing]',    color:'#3AB5D4' },
    { id:'listen',    label:'Listen',    speech:'Listen please',    image:'[AAC: ear]',              color:'#7C6AE0' },
    { id:'great_job', label:'Great Job!',speech:'Great job!',       image:'[AAC: thumbs up star]',   color:'#FFD73C' },
  ],
}

export const SENTENCE_STARTERS = [
  { id:'i_want',  label:'I want',  speech:'I want'  },
  { id:'i_need',  label:'I need',  speech:'I need'  },
  { id:'i_feel',  label:'I feel',  speech:'I feel'  },
  { id:'i_see',   label:'I see',   speech:'I see'   },
  { id:'i_like',  label:'I like',  speech:'I like'  },
  { id:'i_dont',  label:"I don't", speech:"I don't" },
  { id:'can_i',   label:'Can I',   speech:'Can I'   },
  { id:'help_me', label:'Help me', speech:'Help me' },
  { id:'please',  label:'Please',  speech:'Please'  },
]

export const SCHEDULE_ITEMS = [
  { id:'sch_wake',      label:'Wake Up',     image:'[SCHEDULE: sun rising]',       color:'#FFD73C' },
  { id:'sch_breakfast', label:'Breakfast',   image:'[SCHEDULE: breakfast bowl]',   color:'#E8A030' },
  { id:'sch_brush',     label:'Brush Teeth', image:'[SCHEDULE: toothbrush]',       color:'#3AB5D4' },
  { id:'sch_dress',     label:'Get Dressed', image:'[SCHEDULE: clothes]',          color:'#C4A035' },
  { id:'sch_school',    label:'School',      image:'[SCHEDULE: school building]',  color:'#3AB5D4' },
  { id:'sch_therapy',   label:'Therapy',     image:'[SCHEDULE: caring person]',    color:'#9B6AE0' },
  { id:'sch_lunch',     label:'Lunch',       image:'[SCHEDULE: lunch plate]',      color:'#3A9E5A' },
  { id:'sch_play',      label:'Play Time',   image:'[SCHEDULE: playground]',       color:'#E8A030' },
  { id:'sch_quiet',     label:'Quiet Time',  image:'[SCHEDULE: calm room]',        color:'#7C6AE0' },
  { id:'sch_snack',     label:'Snack',       image:'[SCHEDULE: snack plate]',      color:'#C4A035' },
  { id:'sch_homework',  label:'Homework',    image:'[SCHEDULE: desk with books]',  color:'#3AB5D4' },
  { id:'sch_dinner',    label:'Dinner',      image:'[SCHEDULE: dinner table]',     color:'#E8A030' },
  { id:'sch_bath',      label:'Bath',        image:'[SCHEDULE: bathtub]',          color:'#3AB5D4' },
  { id:'sch_bedtime',   label:'Bedtime',     image:'[SCHEDULE: moon and stars]',   color:'#3A3A7C' },
  { id:'sch_ceonis',    label:'Ceonis Time', image:'[SCHEDULE: ceonis app icon]',  color:'#7C6AE0' },
]
